### ISSUE TITLE
Wizard gear not supposed to be destroyed when it runs out of durability

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#10]
It is supposed to consume its stored mana, then become useless until charged again.

I have confirmed failure with `Wizard Hat ebwizardry:wizard_hat`

**Comment by nicwatson** [comment]
Bug in Wizardry itself: https://github.com/Electroblob77/Wizardry/issues/294
Tagging wontfix until they update.
Leaving open to remind me to check for updates from time to time.

**Comment by nicwatson** [comment]
They say it's fixed in Wizardry 4.2.6, which is now in the modpack as of 1.1.0. Can you confirm?

**Comment by nicwatson** [comment]
Confirmed fixed.
