### ISSUE TITLE
Mining Backpack collects ink sacks

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#15]
Maybe this is intended but seems pretty weird for a mining backpack.

**Comment by nicwatson** [comment]
It looks like _all vanilla dyes_ will be collected by the miner's backpack.
My best guess for why this is happening is that the backpack is intended to be able to pick up lapis lazuli gems. However, all dyes share the same item ID with different metadata -- lapis is minecraft:dye#4 and ink sac is minecraft:dye#0. The miner's backpack must be programmed to filter on ID only and not check metadata.
Anyway, issue lies with Forestry. Not practical to patch this on our end.
