### ISSUE TITLE
Wrenches do not seem to turn blocks

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#16]
This is from Bart.

`Wrenches do not seem to turn blocks... tried wooden wrench, magneticraft wrench and forestry wrench.`

**Comment by nicwatson** [comment]
I am able to rotate blocks with the following wrenches: Monkey Wrench (platforms:wrench), Wrench (base:wrench), Wooden Wrench (chiselsandbits:wrench_wood), Wrench (forestry:wrench).

I tried it in the same place where the breaker doesn't work, and rotation still worked, so it's not a minecolonies issue.

The following wrenches do not have a rotation function: Laser Wrench (actuallyadditions), Wrench (Magneticraft). Integrated Dynamics wrench appears to be genuinely broken.
It looks like it's rotating the block but then it instantly reverts. So, don't use that one.

**Comment by nicwatson** [comment]
Clarified: He wanted to rotate brick textures, but wrenches can't rotate blocks that don't have an EnumFacing blockstate property. Will investigate adding alternate chisel textures instead.
