### ISSUE TITLE
In a deconstruction table I can repeatedly deconstruct iron armor into heavy radiation shielding and iron armor

### ISSUE THREAD

**Issue by nicwatson** [nicwatson/siegertsmiasma#2]
Specifically I tested with an Iron Chestplate found in a ungeon with an enchantment.

I'm pretty sure the dev isn't intending to release a 1.12.2 update.
Some thoughts: I can make the IE grinder turn dyed wools into dyes. The IE arc furnace can already be used to recycle metal objects, with the amount of material returned being proportional to the condition of the item (it's also an expensive machine that requires regular maintenance and a lot of power so that keeps it from being too OP).

**Comment by ramou** [comment]
A Hopper yields a minecart. A minecart yields a hopper and a minecart.

**Comment by nicwatson** [comment]
Deconstruction Table mod removed in 1.1.0
