### ISSUE TITLE
Fruit Basket supports slabs of any wood, but requires specific pressure plate

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#22]
`Fruit Basket ccokingforblockheads:fruit_basket` insists on an `Oak Pressure Plate minecraft:wooden_pressure_plate` instead of allowing for any wooden pressure plate. It allows for any wooden slabs to be used in the recipe, and I would like the same logic applied for the pressure plate.

**Comment by nicwatson** [comment]
I thought this would be easy, but it turns out that none of the pressure plates have oredict entries, meaning I would have to add a separate recipe for each other type of pressure plate. Consequently, this is going to have to go to the bottom of the triage.
