### ISSUE TITLE
Pouring liquid glass into ingot tray makes regular, not clear glass panes

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#26]
Bart reported:
`pouring liquid glass into ingot tray in tinkers should make clear glass panes but it only makes regular glass panes. The glass blocks work fine however.`

**Comment by nicwatson** [comment]
We've determined that clear glass panes no longer exist in our version of Tinker's Construct, which is why they can't be created. Clear glass blocks still exist.
