### ISSUE TITLE
Unexpected Pollution

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#30]
TLDR: killing deer and pigs makes pollution, in spite of us being under the impression domestic mob slaughter is safe. Killing squid seems to pollute water. We think this might not be as intended.

Darren wrote:
```
Bart noted that slaughtering domestic mobs is not supposed to produce pollution, 
but slaughtering deer and pigs produces a ton ... Also, why does killing a squid pollute
the water? Not necessarily suggesting this should be changed, but trying to plan
(rereading Giedion on the great Chicago stockyards ...). Still have not got ducts, pumps
and chimneys working perfectly. Does a pump need to go directly under a chimney for
it to work?
```

**Comment by nicwatson** [comment]
Slaughtering passive mods is supposed to create pollution.

Tips:
The carbon is easily reabsorbed in the environment, though it does mean you have to mow the grass more often. Sulfur is more of a problem but builds slowly. For open-air ranching, I recommend the deploying the extendable pollutant pump/pipe + a filter, on a temporary/mobile or permanent basis. It will pull pollution blocks from the sky back to ground level where they can be filtered.
